[project]
name = "work"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "delta-sharing>=1.3.2",
    "jupyterlab>=4.3.6",
    "matplotlib>=3.10.1",
    "pyspark>=3.5.5",
]
